### ISSUE TITLE
string类型带有特殊字符的都无法正常的导出

### ISSUE THREAD

**Issue by shimaoye** [teddyzhang29/ExcelParser#1]
配置表
string
Des
描述
“游戏名称”
123@123.com
100%
*注：警告
名字{0}；等级{1}；
等级%d，类型%d，名字%s

实际导出JSON
[
  {
    "Id": 1,
    "Des": "“"
  },
  {
    "Id": 2,
    "Des": "123"
  },
  {
    "Id": 3,
    "Des": "1"
  },
  {
    "Id": 4,
    "Des": "*"
  },
  {
    "Id": 5,
    "Des": "名字"
  },
  {
    "Id": 6,
    "Des": "等级"
  }
]

**Comment by shimaoye** [comment]
<color=#5cacee>%s</color> 
<size=18>%s</color> 
像UGUI的txt文本常用的   都没办法使用了

**Comment by teddyzhang29** [comment]
抱歉刚看到， 好的最近有点忙，有空我看下。

发自我的 iPhone

**Comment by teddyzhang29** [comment]
修复了
